///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ASMTraining.TestCases.Competency_Training
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CompetencyTraining recording.
    /// </summary>
    [TestModule("45006ebf-6692-44f1-a6d3-d41891acb766", ModuleType.Recording, 1)]
    public partial class CompetencyTraining : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ASMTraining.ASMTrainingRepository repository.
        /// </summary>
        public static ASMTraining.ASMTrainingRepository repo = ASMTraining.ASMTrainingRepository.Instance;

        static CompetencyTraining instance = new CompetencyTraining();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CompetencyTraining()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CompetencyTraining Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Content.CompetencyTraining' at Center", repo.ASMTraining.Content.CompetencyTrainingInfo, new RecordItemIndex(0));
            repo.ASMTraining.Content.CompetencyTraining.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=389,Height=74}) on item 'ASMTraining.CompetencyTraining_HeaderLogo'.", repo.ASMTraining.CompetencyTraining_HeaderLogoInfo, new RecordItemIndex(1));
            Validate.ContainsImage(repo.ASMTraining.CompetencyTraining_HeaderLogoInfo, CompetencyTraining_HeaderLogo_Screenshot1, CompetencyTraining_HeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.visitCompetencyTrainingItem();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select DSF') on item 'ASMTraining.Validate_DsfScreen'.", repo.ASMTraining.Validate_DsfScreenInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ASMTraining.Validate_DsfScreenInfo, "Text", "Please select DSF");
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.visitCompetencyTrainingItem();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select shop') on item 'ASMTraining.Validate_SelectShopScreen'.", repo.ASMTraining.Validate_SelectShopScreenInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ASMTraining.Validate_SelectShopScreenInfo, "Text", "Please select shop");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.ScorePanel' at Center", repo.ASMTraining.ScorePanelInfo, new RecordItemIndex(6));
            repo.ASMTraining.ScorePanel.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select shop') on item 'ASMTraining.Validate_SelectShop_Screen'.", repo.ASMTraining.Validate_SelectShop_ScreenInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ASMTraining.Validate_SelectShop_ScreenInfo, "Text", "Please select shop");
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.visitCompetencyTrainingItem();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Start Training') on item 'ASMTraining.Validate_StartTrainingScreen'.", repo.ASMTraining.Validate_StartTrainingScreenInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ASMTraining.Validate_StartTrainingScreenInfo, "Text", "Start Training");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.NextClickBar' at Center", repo.ASMTraining.NextClickBarInfo, new RecordItemIndex(10));
            repo.ASMTraining.NextClickBar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Validate_OkButton' at Center", repo.ASMTraining.Validate_OkButtonInfo, new RecordItemIndex(11));
            repo.ASMTraining.Validate_OkButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.TakeShopFascia' at Center", repo.ASMTraining.TakeShopFasciaInfo, new RecordItemIndex(12));
            repo.ASMTraining.TakeShopFascia.Touch();
            Delay.Milliseconds(500);
            
            UserCodeCollection.UserCode.takePhotoButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DonePhotoButton' at Center", repo.ASMTraining.DonePhotoButtonInfo, new RecordItemIndex(14));
            repo.ASMTraining.DonePhotoButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.NextClickBar' at Center", repo.ASMTraining.NextClickBarInfo, new RecordItemIndex(15));
            repo.ASMTraining.NextClickBar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'ASMTraining.CompetencyTraining_ListView'.", repo.ASMTraining.CompetencyTraining_ListViewInfo, new RecordItemIndex(17));
            repo.ASMTraining.CompetencyTraining_ListView.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SaveTrainingButton' at Center", repo.ASMTraining.SaveTrainingButtonInfo, new RecordItemIndex(18));
            repo.ASMTraining.SaveTrainingButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Validate_OkButton' at Center", repo.ASMTraining.Validate_OkButtonInfo, new RecordItemIndex(19));
            repo.ASMTraining.Validate_OkButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'ASMTraining.CompetencyTraining_ListView'.", repo.ASMTraining.CompetencyTraining_ListViewInfo, new RecordItemIndex(20));
            repo.ASMTraining.CompetencyTraining_ListView.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List.RatingICESteps' at Center", repo.ASMTraining.List.RatingICEStepsInfo, new RecordItemIndex(21));
            repo.ASMTraining.List.RatingICESteps.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Rate DSF') on item 'ASMTraining.Validate_RatingICEScreen'.", repo.ASMTraining.Validate_RatingICEScreenInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.ASMTraining.Validate_RatingICEScreenInfo, "Text", "Rate DSF");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.RouteManagement' at Center", repo.ASMTraining.RouteManagementInfo, new RecordItemIndex(23));
            repo.ASMTraining.RouteManagement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.NeedImprovement' at Center", repo.ASMTraining.List1.NeedImprovementInfo, new RecordItemIndex(24));
            repo.ASMTraining.List1.NeedImprovement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Standard' at Center", repo.ASMTraining.List1.StandardInfo, new RecordItemIndex(25));
            repo.ASMTraining.List1.Standard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Develped' at Center", repo.ASMTraining.List1.DevelpedInfo, new RecordItemIndex(26));
            repo.ASMTraining.List1.Develped.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.RouteManagement' at Center", repo.ASMTraining.RouteManagementInfo, new RecordItemIndex(27));
            repo.ASMTraining.RouteManagement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.PlanTheDay_PriorityOfTheDay' at Center", repo.ASMTraining.List1.PlanTheDay_PriorityOfTheDayInfo, new RecordItemIndex(28));
            repo.ASMTraining.List1.PlanTheDay_PriorityOfTheDay.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.NeedImprovement' at Center", repo.ASMTraining.List1.NeedImprovementInfo, new RecordItemIndex(29));
            repo.ASMTraining.List1.NeedImprovement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Standard' at Center", repo.ASMTraining.List1.StandardInfo, new RecordItemIndex(30));
            repo.ASMTraining.List1.Standard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Develped' at Center", repo.ASMTraining.List1.DevelpedInfo, new RecordItemIndex(31));
            repo.ASMTraining.List1.Develped.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.PlanTheDay_PriorityOfTheDay' at Center", repo.ASMTraining.List1.PlanTheDay_PriorityOfTheDayInfo, new RecordItemIndex(32));
            repo.ASMTraining.List1.PlanTheDay_PriorityOfTheDay.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.OutletStockCheck' at Center", repo.ASMTraining.List1.OutletStockCheckInfo, new RecordItemIndex(33));
            repo.ASMTraining.List1.OutletStockCheck.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.NeedImprovement' at Center", repo.ASMTraining.List1.NeedImprovementInfo, new RecordItemIndex(34));
            repo.ASMTraining.List1.NeedImprovement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Standard' at Center", repo.ASMTraining.List1.StandardInfo, new RecordItemIndex(35));
            repo.ASMTraining.List1.Standard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Develped' at Center", repo.ASMTraining.List1.DevelpedInfo, new RecordItemIndex(36));
            repo.ASMTraining.List1.Develped.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.OutletStockCheck' at Center", repo.ASMTraining.List1.OutletStockCheckInfo, new RecordItemIndex(37));
            repo.ASMTraining.List1.OutletStockCheck.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Merchandising' at Center", repo.ASMTraining.List1.MerchandisingInfo, new RecordItemIndex(38));
            repo.ASMTraining.List1.Merchandising.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.NeedImprovement' at Center", repo.ASMTraining.List1.NeedImprovementInfo, new RecordItemIndex(39));
            repo.ASMTraining.List1.NeedImprovement.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Standard' at Center", repo.ASMTraining.List1.StandardInfo, new RecordItemIndex(40));
            repo.ASMTraining.List1.Standard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Develped' at Center", repo.ASMTraining.List1.DevelpedInfo, new RecordItemIndex(41));
            repo.ASMTraining.List1.Develped.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List1.Merchandising' at Center", repo.ASMTraining.List1.MerchandisingInfo, new RecordItemIndex(42));
            repo.ASMTraining.List1.Merchandising.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.RatingICE_BackButton' at Center", repo.ASMTraining.RatingICE_BackButtonInfo, new RecordItemIndex(43));
            repo.ASMTraining.RatingICE_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List.FieldSalesCoaching' at Center", repo.ASMTraining.List.FieldSalesCoachingInfo, new RecordItemIndex(45));
            repo.ASMTraining.List.FieldSalesCoaching.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Field Sales Coaching') on item 'ASMTraining.Validate_FieldSalesScreen'.", repo.ASMTraining.Validate_FieldSalesScreenInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ASMTraining.Validate_FieldSalesScreenInfo, "Text", "Field Sales Coaching");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.TakePicture' at Center", repo.ASMTraining.TakePictureInfo, new RecordItemIndex(47));
            repo.ASMTraining.TakePicture.Touch();
            Delay.Milliseconds(500);
            
            UserCodeCollection.UserCode.takePhotoButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DonePhotoButton' at Center", repo.ASMTraining.DonePhotoButtonInfo, new RecordItemIndex(49));
            repo.ASMTraining.DonePhotoButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.FieldScales_BackButton' at Center", repo.ASMTraining.FieldScales_BackButtonInfo, new RecordItemIndex(50));
            repo.ASMTraining.FieldScales_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(51));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List.CapturingPictureOfSuccess' at Center", repo.ASMTraining.List.CapturingPictureOfSuccessInfo, new RecordItemIndex(52));
            repo.ASMTraining.List.CapturingPictureOfSuccess.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Capturing Picture of Success') on item 'ASMTraining.Validate_CapturingPictureScreen'.", repo.ASMTraining.Validate_CapturingPictureScreenInfo, new RecordItemIndex(53));
            Validate.AttributeEqual(repo.ASMTraining.Validate_CapturingPictureScreenInfo, "Text", "Capturing Picture of Success");
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.capturingPictureList();
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.takePhotoButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DonePhotoButton' at Center", repo.ASMTraining.DonePhotoButtonInfo, new RecordItemIndex(56));
            repo.ASMTraining.DonePhotoButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.CapturingPicture_BackButton' at Center", repo.ASMTraining.CapturingPicture_BackButtonInfo, new RecordItemIndex(57));
            repo.ASMTraining.CapturingPicture_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(58));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List.MarketIntelligence' at Center", repo.ASMTraining.List.MarketIntelligenceInfo, new RecordItemIndex(59));
            repo.ASMTraining.List.MarketIntelligence.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Market Intelligence (Optional)') on item 'ASMTraining.Validate_MarketIntelligenceScreen'.", repo.ASMTraining.Validate_MarketIntelligenceScreenInfo, new RecordItemIndex(60));
            Validate.AttributeEqual(repo.ASMTraining.Validate_MarketIntelligenceScreenInfo, "Text", "Market Intelligence (Optional)");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.TakePicture' at Center", repo.ASMTraining.TakePictureInfo, new RecordItemIndex(61));
            repo.ASMTraining.TakePicture.Touch();
            Delay.Milliseconds(500);
            
            UserCodeCollection.UserCode.takePhotoButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DonePhotoButton' at Center", repo.ASMTraining.DonePhotoButtonInfo, new RecordItemIndex(63));
            repo.ASMTraining.DonePhotoButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.MarketIntelligence_BackButton' at Center", repo.ASMTraining.MarketIntelligence_BackButtonInfo, new RecordItemIndex(64));
            repo.ASMTraining.MarketIntelligence_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(65));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.List.Remarks' at Center", repo.ASMTraining.List.RemarksInfo, new RecordItemIndex(66));
            repo.ASMTraining.List.Remarks.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Enter Remarks') on item 'ASMTraining.Validate_RemarksScreen'.", repo.ASMTraining.Validate_RemarksScreenInfo, new RecordItemIndex(67));
            Validate.AttributeEqual(repo.ASMTraining.Validate_RemarksScreenInfo, "Text", "Enter Remarks");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SubmitRemarks' at Center", repo.ASMTraining.SubmitRemarksInfo, new RecordItemIndex(68));
            repo.ASMTraining.SubmitRemarks.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Validate_OkButton' at Center", repo.ASMTraining.Validate_OkButtonInfo, new RecordItemIndex(69));
            repo.ASMTraining.Validate_OkButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Remarks' on item 'ASMTraining.Remark_EditText'.", repo.ASMTraining.Remark_EditTextInfo, new RecordItemIndex(70));
            repo.ASMTraining.Remark_EditText.Element.SetAttributeValue("Text", "Remarks");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SubmitRemarks' at Center", repo.ASMTraining.SubmitRemarksInfo, new RecordItemIndex(71));
            repo.ASMTraining.SubmitRemarks.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Validate_OkButton' at Center", repo.ASMTraining.Validate_OkButtonInfo, new RecordItemIndex(72));
            repo.ASMTraining.Validate_OkButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Training Steps') on item 'ASMTraining.Validate_TrainingStepsScreen'.", repo.ASMTraining.Validate_TrainingStepsScreenInfo, new RecordItemIndex(73));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TrainingStepsScreenInfo, "Text", "Training Steps");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'ASMTraining.CompetencyTraining_ListView'.", repo.ASMTraining.CompetencyTraining_ListViewInfo, new RecordItemIndex(74));
            repo.ASMTraining.CompetencyTraining_ListView.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SaveTrainingButton' at Center", repo.ASMTraining.SaveTrainingButtonInfo, new RecordItemIndex(75));
            repo.ASMTraining.SaveTrainingButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='DSF Rating Summery') on item 'ASMTraining.Validate_DSFRatingSummaryScreen'.", repo.ASMTraining.Validate_DSFRatingSummaryScreenInfo, new RecordItemIndex(76));
            Validate.AttributeEqual(repo.ASMTraining.Validate_DSFRatingSummaryScreenInfo, "Text", "DSF Rating Summery");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DSFRatingSummery_BackButton' at Center", repo.ASMTraining.DSFRatingSummery_BackButtonInfo, new RecordItemIndex(77));
            repo.ASMTraining.DSFRatingSummery_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select shop') on item 'ASMTraining.Validate_SelectShop_Screen'.", repo.ASMTraining.Validate_SelectShop_ScreenInfo, new RecordItemIndex(78));
            Validate.AttributeEqual(repo.ASMTraining.Validate_SelectShop_ScreenInfo, "Text", "Please select shop");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Select_Shop_BackButton' at Center", repo.ASMTraining.Select_Shop_BackButtonInfo, new RecordItemIndex(79));
            repo.ASMTraining.Select_Shop_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select shop') on item 'ASMTraining.Validate_SelectShopScreen'.", repo.ASMTraining.Validate_SelectShopScreenInfo, new RecordItemIndex(80));
            Validate.AttributeEqual(repo.ASMTraining.Validate_SelectShopScreenInfo, "Text", "Please select shop");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SelectShop_BackButton' at Center", repo.ASMTraining.SelectShop_BackButtonInfo, new RecordItemIndex(81));
            repo.ASMTraining.SelectShop_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Please select DSF') on item 'ASMTraining.Validate_DsfScreen'.", repo.ASMTraining.Validate_DsfScreenInfo, new RecordItemIndex(82));
            Validate.AttributeEqual(repo.ASMTraining.Validate_DsfScreenInfo, "Text", "Please select DSF");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.SelectDSF_BackButton' at Center", repo.ASMTraining.SelectDSF_BackButtonInfo, new RecordItemIndex(83));
            repo.ASMTraining.SelectDSF_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=389,Height=74}) on item 'ASMTraining.CompetencyTraining_HeaderLogo'.", repo.ASMTraining.CompetencyTraining_HeaderLogoInfo, new RecordItemIndex(84));
            Validate.ContainsImage(repo.ASMTraining.CompetencyTraining_HeaderLogoInfo, CompetencyTraining_HeaderLogo_Screenshot1_2, CompetencyTraining_HeaderLogo_Screenshot1_2_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.CompetencyDetailScreen_BackButton' at Center", repo.ASMTraining.CompetencyDetailScreen_BackButtonInfo, new RecordItemIndex(85));
            repo.ASMTraining.CompetencyDetailScreen_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.ASMTraining_Logo'.", repo.ASMTraining.ASMTraining_LogoInfo, new RecordItemIndex(86));
            Validate.ContainsImage(repo.ASMTraining.ASMTraining_LogoInfo, ASMTraining_Logo_Screenshot1, ASMTraining_Logo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage CompetencyTraining_HeaderLogo_Screenshot1
        { get { return repo.ASMTraining.CompetencyTraining_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 389, 74)); } }

        Imaging.FindOptions CompetencyTraining_HeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage CompetencyTraining_HeaderLogo_Screenshot1_2
        { get { return repo.ASMTraining.CompetencyTraining_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 389, 74)); } }

        Imaging.FindOptions CompetencyTraining_HeaderLogo_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ASMTraining_Logo_Screenshot1
        { get { return repo.ASMTraining.ASMTraining_LogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions ASMTraining_Logo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
