///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ASMTraining.TestCases.CCSD_E_Book
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VisitRegionalRanking recording.
    /// </summary>
    [TestModule("ea557f92-158a-442d-9960-6ea67354d529", ModuleType.Recording, 1)]
    public partial class VisitRegionalRanking : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ASMTraining.ASMTrainingRepository repository.
        /// </summary>
        public static ASMTraining.ASMTrainingRepository repo = ASMTraining.ASMTrainingRepository.Instance;

        static VisitRegionalRanking instance = new VisitRegionalRanking();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VisitRegionalRanking()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VisitRegionalRanking Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Regional Ranking') on item 'ASMTraining.Validate_RegionalRankingScreen'.", repo.ASMTraining.Validate_RegionalRankingScreenInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ASMTraining.Validate_RegionalRankingScreenInfo, "Text", "Regional Ranking");
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.visitRegion();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='ASM Ranking') on item 'ASMTraining.Validate_AsmRankingScreen'.", repo.ASMTraining.Validate_AsmRankingScreenInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ASMTraining.Validate_AsmRankingScreenInfo, "Text", "ASM Ranking");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.AsmRanking_BackButton' at Center", repo.ASMTraining.AsmRanking_BackButtonInfo, new RecordItemIndex(3));
            repo.ASMTraining.AsmRanking_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Regional Ranking') on item 'ASMTraining.Validate_RegionalRankingScreen'.", repo.ASMTraining.Validate_RegionalRankingScreenInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ASMTraining.Validate_RegionalRankingScreenInfo, "Text", "Regional Ranking");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.RegionalRanking_BackButton' at Center", repo.ASMTraining.RegionalRanking_BackButtonInfo, new RecordItemIndex(5));
            repo.ASMTraining.RegionalRanking_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Zonal RANKING') on item 'ASMTraining.Validate_ZonalRankingScreen'.", repo.ASMTraining.Validate_ZonalRankingScreenInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ASMTraining.Validate_ZonalRankingScreenInfo, "Text", "Zonal RANKING");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
