///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ASMTraining.TestCases.Training_Updates
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TrainingUpdates recording.
    /// </summary>
    [TestModule("0a5ceb60-cda0-4257-ad56-88006e2e810e", ModuleType.Recording, 1)]
    public partial class TrainingUpdates : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ASMTraining.ASMTrainingRepository repository.
        /// </summary>
        public static ASMTraining.ASMTrainingRepository repo = ASMTraining.ASMTrainingRepository.Instance;

        static TrainingUpdates instance = new TrainingUpdates();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TrainingUpdates()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TrainingUpdates Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Content.TrainingUpdate' at Center", repo.ASMTraining.Content.TrainingUpdateInfo, new RecordItemIndex(0));
            repo.ASMTraining.Content.TrainingUpdate.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.TrainingUpdates_HeaderLogo'.", repo.ASMTraining.TrainingUpdates_HeaderLogoInfo, new RecordItemIndex(1));
            Validate.ContainsImage(repo.ASMTraining.TrainingUpdates_HeaderLogoInfo, TrainingUpdates_HeaderLogo_Screenshot1, TrainingUpdates_HeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Content1.DsfTrainingStats' at Center", repo.ASMTraining.Content1.DsfTrainingStatsInfo, new RecordItemIndex(2));
            repo.ASMTraining.Content1.DsfTrainingStats.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=389,Height=74}) on item 'ASMTraining.Dsf_TopHeaderLogo'.", repo.ASMTraining.Dsf_TopHeaderLogoInfo, new RecordItemIndex(3));
            Validate.ContainsImage(repo.ASMTraining.Dsf_TopHeaderLogoInfo, Dsf_TopHeaderLogo_Screenshot1, Dsf_TopHeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.DsfTraining_BackButton' at Center", repo.ASMTraining.DsfTraining_BackButtonInfo, new RecordItemIndex(4));
            repo.ASMTraining.DsfTraining_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.Content1.CapabilityChamp' at Center", repo.ASMTraining.Content1.CapabilityChampInfo, new RecordItemIndex(5));
            repo.ASMTraining.Content1.CapabilityChamp.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.CapabilityCham_TopHeaderLogo'.", repo.ASMTraining.CapabilityCham_TopHeaderLogoInfo, new RecordItemIndex(6));
            Validate.ContainsImage(repo.ASMTraining.CapabilityCham_TopHeaderLogoInfo, CapabilityCham_TopHeaderLogo_Screenshot1, CapabilityCham_TopHeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.NationalChampions' at Center", repo.ASMTraining.NationalChampionsInfo, new RecordItemIndex(7));
            repo.ASMTraining.NationalChampions.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.NationalChamp_HeaderLogo'.", repo.ASMTraining.NationalChamp_HeaderLogoInfo, new RecordItemIndex(8));
            Validate.ContainsImage(repo.ASMTraining.NationalChamp_HeaderLogoInfo, NationalChamp_HeaderLogo_Screenshot1, NationalChamp_HeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.ASM_NationalChampButton' at Center", repo.ASMTraining.ASM_NationalChampButtonInfo, new RecordItemIndex(9));
            repo.ASMTraining.ASM_NationalChampButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='NATIONAL CHAMPIONS') on item 'ASMTraining.Validate_ASMNationalChampsScreen'.", repo.ASMTraining.Validate_ASMNationalChampsScreenInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ASMTraining.Validate_ASMNationalChampsScreenInfo, "Text", "NATIONAL CHAMPIONS");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.AsmNationalChamp_BackButton' at Center", repo.ASMTraining.AsmNationalChamp_BackButtonInfo, new RecordItemIndex(11));
            repo.ASMTraining.AsmNationalChamp_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.NationalChamp_HeaderLogo'.", repo.ASMTraining.NationalChamp_HeaderLogoInfo, new RecordItemIndex(12));
            Validate.ContainsImage(repo.ASMTraining.NationalChamp_HeaderLogoInfo, NationalChamp_HeaderLogo_Screenshot1_2, NationalChamp_HeaderLogo_Screenshot1_2_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.TSE_NationalChampButton' at Center", repo.ASMTraining.TSE_NationalChampButtonInfo, new RecordItemIndex(13));
            repo.ASMTraining.TSE_NationalChampButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='NATIONAL CHAMPIONS') on item 'ASMTraining.Validate_TSENationalChampsScreen'.", repo.ASMTraining.Validate_TSENationalChampsScreenInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ASMTraining.Validate_TSENationalChampsScreenInfo, "Text", "NATIONAL CHAMPIONS");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.TseNationalChamp_BackButton' at Center", repo.ASMTraining.TseNationalChamp_BackButtonInfo, new RecordItemIndex(15));
            repo.ASMTraining.TseNationalChamp_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.NationalChamp_HeaderLogo'.", repo.ASMTraining.NationalChamp_HeaderLogoInfo, new RecordItemIndex(16));
            Validate.ContainsImage(repo.ASMTraining.NationalChamp_HeaderLogoInfo, NationalChamp_HeaderLogo_Screenshot1_3, NationalChamp_HeaderLogo_Screenshot1_3_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ASMTraining'.", repo.ASMTraining.SelfInfo, new RecordItemIndex(17));
            repo.ASMTraining.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.ZonalChampions' at Center", repo.ASMTraining.ZonalChampionsInfo, new RecordItemIndex(18));
            repo.ASMTraining.ZonalChampions.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=389,Height=74}) on item 'ASMTraining.ZoneListScreen.ZonalChamp_TopHeaderLogo'.", repo.ASMTraining.ZoneListScreen.ZonalChamp_TopHeaderLogoInfo, new RecordItemIndex(19));
            Validate.ContainsImage(repo.ASMTraining.ZoneListScreen.ZonalChamp_TopHeaderLogoInfo, ZonalChamp_TopHeaderLogo_Screenshot1, ZonalChamp_TopHeaderLogo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            UserCodeCollection.UserCode.visitZonalChamps();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ASMTraining.ZoneListScreen.ZonalChamp_BackButton' at Center", repo.ASMTraining.ZoneListScreen.ZonalChamp_BackButtonInfo, new RecordItemIndex(21));
            repo.ASMTraining.ZoneListScreen.ZonalChamp_BackButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ASMTraining'.", repo.ASMTraining.SelfInfo, new RecordItemIndex(22));
            repo.ASMTraining.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ASMTraining'.", repo.ASMTraining.SelfInfo, new RecordItemIndex(23));
            repo.ASMTraining.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=373,Height=310}) on item 'ASMTraining.ASMTraining_Logo'.", repo.ASMTraining.ASMTraining_LogoInfo, new RecordItemIndex(24));
            Validate.ContainsImage(repo.ASMTraining.ASMTraining_LogoInfo, ASMTraining_Logo_Screenshot1, ASMTraining_Logo_Screenshot1_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage TrainingUpdates_HeaderLogo_Screenshot1
        { get { return repo.ASMTraining.TrainingUpdates_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions TrainingUpdates_HeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Dsf_TopHeaderLogo_Screenshot1
        { get { return repo.ASMTraining.Dsf_TopHeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 389, 74)); } }

        Imaging.FindOptions Dsf_TopHeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage CapabilityCham_TopHeaderLogo_Screenshot1
        { get { return repo.ASMTraining.CapabilityCham_TopHeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions CapabilityCham_TopHeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage NationalChamp_HeaderLogo_Screenshot1
        { get { return repo.ASMTraining.NationalChamp_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions NationalChamp_HeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage NationalChamp_HeaderLogo_Screenshot1_2
        { get { return repo.ASMTraining.NationalChamp_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions NationalChamp_HeaderLogo_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage NationalChamp_HeaderLogo_Screenshot1_3
        { get { return repo.ASMTraining.NationalChamp_HeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions NationalChamp_HeaderLogo_Screenshot1_3_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ZonalChamp_TopHeaderLogo_Screenshot1
        { get { return repo.ASMTraining.ZoneListScreen.ZonalChamp_TopHeaderLogoInfo.GetScreenshot1(new Rectangle(0, 0, 389, 74)); } }

        Imaging.FindOptions ZonalChamp_TopHeaderLogo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ASMTraining_Logo_Screenshot1
        { get { return repo.ASMTraining.ASMTraining_LogoInfo.GetScreenshot1(new Rectangle(0, 0, 373, 310)); } }

        Imaging.FindOptions ASMTraining_Logo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
